name: macx

on: push

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v2
      # Increment version. Ideally we would like to do it once for all builds,
      # but this is complicated as we want to allow to trigger a nightly by
      # pushing the tag, so this can't be in nightly.yml. One option would be to
      # have another intermediate workflow, but we take the quik & dirty
      # solution: increment it in each workflow and push it in one (linux.yml).
      - name: Increment version
        id: version
        run: |
          version=$(grep "define NIGHTLY" source/LeLib/data.cpp | awk '{ print $3 }')
          let version=${version}+1
          # Mac uses BSD sed where -i takes a parameter (an extension for the
          # backup file, empty string disables backup)
          sed -i '' "s/define NIGHTLY .*/define NIGHTLY $version/" source/LeLib/data.cpp
          version=$(grep "define \(MAJOR\|FEATURE\|NIGHTLY\)" source/LeLib/data.cpp | awk '{ print $3 }' | xargs | sed 's/ /\./g')
          echo "::set-output name=TRSE_VERSION::${version}"
      - uses: actions/setup-node@v1
      - uses: jurplel/install-qt-action@v2
      - run: brew install libomp

      - run: |
          echo "COMPANY = KomSoft" >> TRSE.pro
          echo "QMAKE_TARGET_BUNDLE_PREFIX = com.komsoft" >> TRSE.pro
          qmake TRSE.pro
      - run: |
          make -j 3
          /usr/libexec/PlistBuddy -c "Set :NOTE 'Turbo Rascal Syntax Error IDE'" trse.app/Contents/Info.plist
          /usr/libexec/PlistBuddy -c "Add :CFBundleShortVersionString string ${{ steps.version.outputs.TRSE_VERSION }}" trse.app/Contents/Info.plist

      # https://github.com/marketplace/actions/create-update-release-and-upload-assets

      - run: cd Publish/publish_mac && ./publish_mac.sh nightly
      - uses: ColinPitrat/update-release@master
        with:
          release: nightly
          message: Nightly build
          body: TRSE ${{ steps.version.outputs.TRSE_VERSION }} <br/> The latest automated nightly build of TRSE which succeeded. This is the recommended version to use.
          files: Publish/publish_mac/trse_osx.tar.gz
          prerelease: false
          token: ${{ secrets.TRSE_TOKEN }}

      - name: Build notification
        if: failure()
        uses: adamkdean/simple-slack-notify@master
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          channel: #bugs
          text: "[GitHub Actions Notification] MacOS build failed: ${env.GITHUB_SERVER_URL}/${env.GITHUB_REPOSITORY}/actions/runs/${env.GITHUB_RUN_ID}"
